config/routes.rb
Rails.application.routes.draw do

  resources :positions
  # Routes for main resources
  resources :tags
  resources :org_tags
  resources :organizations
  resources :commitments
  resources :interests
  resources :students
  resources :users
  resources :sessions
  resources :favorite_organizations, only: [:create, :destroy]

  # Set the root url
  root :to => 'home#home'

  # Authentication routes
  get 'home' => 'home#home', as: :home
  get 'user/edit' => 'users#edit', as: :edit_current_user
  get 'signup' => 'students#new', as: :signup
  get 'logout' => 'sessions#destroy', as: :logout
  get 'login' => 'sessions#new', as: :login
  get 'student/dashboard' => 'home#student_dashboard', as: :student_dashboard
  get 'dorm/:name' => 'home#dorm', as: :dorm
  get 'home/:more' => 'home#home', as: :more

end

app/models/org_tag.rb
class OrgTag < ActiveRecord::Base

	# Relationships
  belongs_to :tag
  belongs_to :organization

  scope :for_org, ->(tag) { where(tag_id: tag) }
end

app/controllers/org_tags_controller.rb
class OrgTagsController < ApplicationController
  before_action :set_org_tag, only: [:show, :edit, :update, :destroy]

  # GET /org_tags
  # GET /org_tags.json
  def index
    @org_tags = OrgTag.all
  end

  # GET /org_tags/1
  # GET /org_tags/1.json
  def show
  end

  # GET /org_tags/new
  def new
    @org_tag = OrgTag.new
  end

  # GET /org_tags/1/edit
  def edit
  end

  # POST /org_tags
  # POST /org_tags.json
  def create
    @org_tag = OrgTag.new(org_tag_params)

    respond_to do |format|
      if @org_tag.save
        format.html { redirect_to @org_tag, notice: 'Org tag was successfully created.' }
        format.json { render :show, status: :created, location: @org_tag }
      else
        format.html { render :new }
        format.json { render json: @org_tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /org_tags/1
  # PATCH/PUT /org_tags/1.json
  def update
    respond_to do |format|
      if @org_tag.update(org_tag_params)
        format.html { redirect_to @org_tag, notice: 'Org tag was successfully updated.' }
        format.json { render :show, status: :ok, location: @org_tag }
      else
        format.html { render :edit }
        format.json { render json: @org_tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /org_tags/1
  # DELETE /org_tags/1.json
  def destroy
    @org_tag.destroy
    respond_to do |format|
      format.html { redirect_to org_tags_url, notice: 'Org tag was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_org_tag
      @org_tag = OrgTag.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def org_tag_params
      params.require(:org_tag).permit(:organization_id, :tag_id)
    end
end

app/helpers/org_tags_helper.rb
module OrgTagsHelper
end

app/views/org_tags/_form.html.erb
<%= form_for(@org_tag) do |f| %>
  <% if @org_tag.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@org_tag.errors.count, "error") %> prohibited this org_tag from being saved:</h2>

      <ul>
      <% @org_tag.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :organization_id %><br>
    <%= f.collection_select :organization_id, Organization.alphabetical, :id, :name, prompt: "Select..." %>
  </div>
  <div class="field">
    <%= f.label :tag_id %><br>
    <%= f.collection_select :tag_id, Tag.alphabetical, :id, :name, prompt: "Select..." %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/org_tags/edit.html.erb
<h1>Editing Org Tag</h1>

<%= render 'form' %>

<%= link_to 'Show', @org_tag %> |
<%= link_to 'Back', org_tags_path %>

app/views/org_tags/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Org Tags</h1>

<table>
  <thead>
    <tr>
      <th>Organization</th>
      <th>Tag</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @org_tags.each do |org_tag| %>
      <tr>
        <td><%= org_tag.organization_id %></td>
        <td><%= org_tag.tag_id %></td>
        <td><%= link_to 'Show', org_tag %></td>
        <td><%= link_to 'Edit', edit_org_tag_path(org_tag) %></td>
        <td><%= link_to 'Destroy', org_tag, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Org tag', new_org_tag_path %>

app/views/org_tags/new.html.erb
<h1>New Org Tag</h1>

<%= render 'form' %>

<%= link_to 'Back', org_tags_path %>

app/views/org_tags/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Organization:</strong>
  <%= @org_tag.organization_id %>
</p>

<p>
  <strong>Tag:</strong>
  <%= @org_tag.tag_id %>
</p>

<%= link_to 'Edit', edit_org_tag_path(@org_tag) %> |
<%= link_to 'Back', org_tags_path %>