config/routes.rb
Rails.application.routes.draw do

  resources :positions
  # Routes for main resources
  resources :tags
  resources :org_tags
  resources :organizations
  resources :commitments
  resources :interests
  resources :students
  resources :users
  resources :sessions
  resources :favorite_organizations, only: [:create, :destroy]

  # Set the root url
  root :to => 'home#home'

  # Authentication routes
  get 'home' => 'home#home', as: :home
  get 'user/edit' => 'users#edit', as: :edit_current_user
  get 'signup' => 'students#new', as: :signup
  get 'logout' => 'sessions#destroy', as: :logout
  get 'login' => 'sessions#new', as: :login
  get 'student/dashboard' => 'home#student_dashboard', as: :student_dashboard
  get 'dorm/:name' => 'home#dorm', as: :dorm
  get 'home/:more' => 'home#home', as: :more

end

app/views/partials/_footer.html.erb
<div id="footer">
	
	<%= link_to 'Home', home_path %>&nbsp;&nbsp;::&nbsp;&nbsp;
	
</div>

app/views/partials/_nav.html.erb
<!-- code for nav bar goes here -->
	<nav style="padding-left:310px;background-color:rgb(153,0,0);">
      <div class="nav-wrapper">
        <%= link_to 'CMYou', home_path, { :class=> "brand-logo" } %>
        <ul class="right hide-on-med-and-down">
        <% if current_user.role?(:student) %>
          <li><%= link_to 'Profile', edit_student_path(current_user.student)%></li>
        <%end%>
        	<li><%= link_to 'Logout', logout_path%></li>
        </ul>
      </div>
    </nav>

    <ul id="slide-out" class="side-nav fixed">
      <li><div class="userView">
        <div class="background">
          <%= image_tag 'tartan-min.png', width:"100%" %>
          <!-- <img src="../assets/images/tartan-min.png"> -->
        </div>
        <div class="row">
          <div class="col s6">
            <div class="row">
              <span class="white-text name">
              <% if current_user.role?(:student) %>
              	<%= current_user.student.proper_name %>
              <%end%>
              </span>
              <span class="white-text email">
              	<%= current_user.username %>
              </span>
            </div>
          </div>
        </div>
      </div></li>
      <% if current_user.role?(:student) %>
        <li><%= link_to 'Student Dashboard', student_dashboard_path , style:'color:black;' %></li>
        <li><div class="divider"></div></li>
        <li><%= link_to 'Recommended Orgs.', home_path , style:'color:black;' %></li>
      
      <% elsif current_user.role?(:admin) %>
        <li><%= link_to 'Admin Dashboard', home_path , style:'color:black;' %></li>
        <li><div class="divider"></div></li>
        <li><%= link_to 'All Organizations', organizations_path , style:'color:black;' %></li>
        <li><div class="divider"></div></li>
        <li><%= link_to 'All Users', users_path , style:'color:black;' %></li>
        <li><div class="divider"></div></li>
        <li><%= link_to 'All Tags', tags_path , style:'color:black;' %></li>

      <% elsif current_user.role?(:ra) %>
        <li><%= link_to 'RA Dashboard', home_path , style:'color:black;' %></li>
        <li><div class="divider"></div></li>
      <% end %>
     

    </ul>