config/routes.rb
Rails.application.routes.draw do

  resources :positions
  # Routes for main resources
  resources :tags
  resources :org_tags
  resources :organizations
  resources :commitments
  resources :interests
  resources :students
  resources :users
  resources :sessions
  resources :favorite_organizations, only: [:create, :destroy]

  # Set the root url
  root :to => 'home#home'

  # Authentication routes
  get 'home' => 'home#home', as: :home
  get 'user/edit' => 'users#edit', as: :edit_current_user
  get 'signup' => 'students#new', as: :signup
  get 'logout' => 'sessions#destroy', as: :logout
  get 'login' => 'sessions#new', as: :login
  get 'student/dashboard' => 'home#student_dashboard', as: :student_dashboard
  get 'dorm/:name' => 'home#dorm', as: :dorm
  get 'home/:more' => 'home#home', as: :more

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def home
    more = params[:more]
    if (current_user && current_user.role?(:student))
      recommended_orgs = find_organization_recommendations
      @recommended_orgs = find_organization_recommendations.each_slice(6).to_a[0]

      @recommended_orgs_2 = []
      @more = 0
      if (more == "true")
        @more += 1
        @recommended_orgs_2 = recommended_orgs.each_slice(6).to_a[1]
      end
      
      @student = current_user.student.id

    elsif (current_user)
    #  @recommended_houses = find_house_recommendations
    else
      redirect_to login_path
    end
  end

  def dorm
    @dorm = params[:name]
    @students_= Student.for_dorm(params[:name]).count
    @student_interests = student_interests
  end

  def student_dashboard
    @commitments = current_user.favorite_organizations
    @positions = get_positions
    @stackchart = get_data_for_stackchart
  end


  private

  def get_data_for_stackchart
    list = Array.new

    @commitments.each do |org|
      hash = Hash.new
      hash[org.name] = org.positions.first.hour_commitment

      list.push(hash)
    end

    return list

  end

  def student_interests
    students_ids = Student.for_dorm(params[:name]).map(&:id)
    student_interests = Hash.new
    students_ids.each do |sid|
      interest = Interest.get_interests(sid)
      interest.each do |i|
        if student_interests.has_key?(i.name) 
          student_interests[i.name] += 1
        else
          student_interests[i.name] = 1
        end
      end
    end
    return student_interests
  end

  def get_positions
    fav_orgs = current_user.favorite_organizations
    positions = Array.new
    times_array = Array.new

    fav_orgs.each do |o|
      positions << Position.get_position_from_org_id(o.id).map{|p| p.hour_commitment}
    end

    positions.each do |times|
      times_array.push(times[0])
    end

    return times_array
  end

  def find_organization_recommendations
    tag_ids = match_interests_to_tags
    org_ids = match_tags_to_orgs(tag_ids)
    matching_orgs = find_org_names(org_ids)

    return matching_orgs
  end

  def match_interests_to_tags
    interests = current_user.student.interests
    matching_tags = Hash.new

    interests.each do |i|
      tag = Tag.for_interest(i.name)
      unless (tag.empty? or matching_tags.has_value?(tag[0].id))
        matching_tags[tag[0].id] = tag[0].id 
      end
    end

    return matching_tags

  end

  def match_tags_to_orgs(tag_ids)
    matching_orgs = Array.new

    tag_ids.each do |t|
      matching_orgs += OrgTag.for_org(t).map(&:organization_id)
    end

    return matching_orgs
  end

  def find_org_names(org_ids)
    matching_orgs = Array.new

    org_ids.each do |oi|
      matching_orgs += Organization.for_org(oi).map {|o| [o.id, o.name, o.description]}
    end

    return matching_orgs
  end


end

app/views/home/_admin_dashboard.html.erb
<!-- code for admin dashboard goes here -->
<div id="main2">
	<h4>Admin Dashboard</h4>
</div>

app/views/home/_ra_dashboard.html.erb
<!-- code for ra dashboard goes here -->
<ul class="collection with-header">
	<li class="collection-header"><h4>View Student Analytics By Dorm</h4></li>
	<% Student::DORM_LIST.each do |dorm| %>
	<%= link_to dorm[0], dorm_path(dorm[0]), :class => 'collection-item'%>
	<%end%>
</ul>

app/views/home/_student_interest_form.html.erb
<!-- page to display for first time user with no interests -->
<div id='interest_background'>
<%= image_tag 'cmu_bg.jpg', class: "interest_image" %>
	<div class="interestwrapper">
		<button class="btn waves-effect waves-light" style="background-color:rgb(153,0,0);border-radius:40px;"><%= link_to "Fill Out Your Interests", edit_student_path(@student) %></button>
	</div>
</div>

app/views/home/_student_recommendations.html.erb
<!-- code for student recommendations goes here -->
<div id="main2">
<h4>Recommended Organizations</h4>

	<% if @recommended_orgs.nil? %>
	  <h5><center><i>There are currently no recommended organizations. Please modify your interests and try again! <%= link_to "Edit Interests", new_interest_path %> </i></center></h5>
	<% else %>
		<div class="row">
		  <% @recommended_orgs.each do |org| %>
		    <div class="col s4">
		      <div class="card small">
		        <div class="card-content">
		          <span class="card-title activator grey-text text-darken-4"><b><%=org[1] %></b><i class="mdi-navigation-more-vert right"></i></span>
		          <br>
		          <p style="overflow:hidden;display:-webkit-box;-webkit-line-clamp:3;-webkit-box-orient: vertical;"><%= raw org[2] %></p>
		        </div>

		        <div class="card-action">
							<%= link_to "View Organization", organization_path(org[0]) %>
							
							<% unless current_user.favorite_organizations.exists?(id: org[0]) %>
								
								<%= link_to image_tag('unfavorite.png', size: "35x30", :style => ("padding-left:5px;"), class: "right"), favorite_organizations_path(organization_id: org[0]), method: :post %>
							<% else %>
								<%= link_to image_tag('favorite.jpg', size: "35x30", :style => ("padding-left:5px;"), class: "right"), favorite_organization_path(org[0]), method: :delete %>
							<% end %>
						</div>
		      </div>
		    </div>
		  <% end %>
		</div>

	<% if ((@recommended_orgs_2.nil?) && (@more == 1)) %>
	  <h5><center><i>There are currently no more recommended organizations. Please modify your interests and try again! <%= link_to "Edit Interests", new_interest_path %> </i></center></h5>
	<% else %>
		<div class="row">
		  <% @recommended_orgs_2.each do |org| %>
		    <div class="col s4">
		      <div class="card small">
		        <div class="card-content">
		          <span class="card-title activator grey-text text-darken-4"><b><%=org[1] %></b><i class="mdi-navigation-more-vert right"></i></span>
		          <br>
		          <p style="overflow:hidden;display:-webkit-box;-webkit-line-clamp:3;-webkit-box-orient: vertical;"><%= raw org[2] %></p>
		        </div>

		        <div class="card-action">
							<%= link_to "View Organization", organization_path(org[0]) %>
							
							<% unless current_user.favorite_organizations.exists?(id: org[0]) %>
								
								<%= link_to image_tag('unfavorite.png', size: "35x30", :style => ("padding-left:5px;"), class: "right"), favorite_organizations_path(organization_id: org[0]), method: :post %>
							<% else %>
								<%= link_to image_tag('favorite.jpg', size: "35x30", :style => ("padding-left:5px;"), class: "right"), favorite_organization_path(org[0]), method: :delete %>
							<% end %>
						</div>
		      </div>
		    </div>
		  <% end %>
		</div>
	<% end %>
	  
	  <% if @more == 0 %>
	  	<%= link_to "View More", more_path(:true), :class => "waves-effect waves-light btn-large" %>
	  <% end %>


	<% end %>
</div>

app/views/home/dorm.html.erb
<div id='main2'>

<h4>You're viewing information for <%=@dorm%>...</h4>
<br><br>
<!--<p><%=@student_interests%></p>-->

<div class="row">
	<div class="col s6">
		<div id="container1" style="min-width: 310px; height: 400px; max-width: 600px; margin: 0 auto"></div>
	</div>
	<div id="interests" style="display:none"><%= @student_interests%></div>
	<div class="col s6">
		<div id="container" style="min-width: 310px; height: 400px; margin: 0 auto"></div>
	</div>
</div>

<script>
$(function () {

    // Radialize the colors
    Highcharts.getOptions().colors = Highcharts.map(Highcharts.getOptions().colors, function (color) {
        return {
            radialGradient: {
                cx: 0.5,
                cy: 0.3,
                r: 0.7
            },
            stops: [
                [0, color],
                [1, Highcharts.Color(color).brighten(-0.3).get('rgb')] // darken
            ]
        };
    });

    var hash_string = $('#interests').html();
    var st;
    var interestList = hash_string.split(",");
    console.log(interestList);
    var hash_dict = [];
    for (st in interestList) {
    	console.log(interestList[st]);
    	dict = {};
    	var interest_pattern = /"(.*?)"/;
    	var interest_value = interestList[st].match(interest_pattern);
    	console.log("after matching",interest_value[1]);
    	dict['name'] = interest_value[1];

    	var value_pattern = /\d+/;
    	var real_count = interestList[st].match(value_pattern);
    	console.log("after matching",real_count[0]);
    	dict['y'] = parseInt(real_count[0]);
    	console.log(dict);
    	hash_dict.push(dict);
    }

    // Build the chart
    Highcharts.chart('container1', {
        chart: {
            plotBackgroundColor: null,
            plotBorderWidth: null,
            plotShadow: false,
            type: 'pie'
        },
        title: {
            text: 'Student Interests By Dormitory'
        },
        tooltip: {
            pointFormat: '{series.name}: <b>{point.percentage:.1f}%</b>'
        },
        plotOptions: {
            pie: {
                allowPointSelect: true,
                cursor: 'pointer',
                dataLabels: {
                    enabled: true,
                    format: '<b>{point.name}</b>: {point.percentage:.1f} %',
                    style: {
                        color: (Highcharts.theme && Highcharts.theme.contrastTextColor) || 'black'
                    },
                    connectorColor: 'silver'
                }
            }
        },
        series: [{
            name: 'Interests',
            data: hash_dict
        }]
    });
});

$(function () {

	var hash_string = $('#interests').html();
    var st;
    var interestList = hash_string.split(",");
    console.log(interestList);
    var hash_dict = [];
    for (st in interestList) {
    	console.log(interestList[st]);
    	dict = {};
    	var interest_pattern = /"(.*?)"/;
    	var interest_value = interestList[st].match(interest_pattern);
    	console.log("after matching",interest_value[1]);
    	dict['name'] = interest_value[1];

    	var value_pattern = /\d+/;
    	var real_count = interestList[st].match(value_pattern);
    	console.log("after matching",real_count[0]);
    	dict['y'] = parseInt(real_count[0]);
    	console.log(dict);
    	hash_dict.push(dict);
    }

    // Create the chart
    Highcharts.chart('container', {
        chart: {
            type: 'column'
        },
        title: {
            text: 'Student Interests By Dormitory'
        },
        xAxis: {
            type: 'category'
        },
        yAxis: {
            title: {
                text: 'Number Of Students'
            }

        },
        legend: {
            enabled: false
        },
        plotOptions: {
            series: {
                borderWidth: 0,
                dataLabels: {
                    enabled: true,
                    format: '{point.y}'
                }
            }
        },

        tooltip: {
            headerFormat: '<span style="font-size:11px">{series.name}</span><br>',
            pointFormat: '<span style="color:{point.color}">{point.name}</span>: <b>{point.y:.2f}%</b> of total<br/>'
        },

        series: [{
            name: 'Brands',
            colorByPoint: true,
            data: hash_dict
        }]
    });
});
</script>
</div>

app/views/home/home.html.erb
<!-- home page for users that are logged in -->

<% if current_user.role?(:student) %>
  <div id="main-container" class="container-fluid">
    <div id="main content" class="col-xs-12">
      <% if current_user.student.interests.empty? %>
        <%= render 'student_interest_form' %>
      <% else %>
        <%= render 'student_recommendations' %>
      <% end %>
    </div>
  </div>

<% elsif current_user.role?(:ra) %>
  <div id="main-container" class="container-fluid">
    <div id="main content" class="col-xs-12">
      <%= render 'ra_dashboard' %>
    </div>
  </div>

<% elsif current_user.role?(:admin) %>
  <div id="main-container" class="container-fluid">
    <div id="main content" class="col-xs-12">
      <%= render 'admin_dashboard' %>
    </div>
  </div>

<% end %>

app/views/home/student_dashboard.html.erb
<!-- code for student recommendations goes here -->
<div id="main2">

<% if @commitments.empty? %>
	<h5>You have not favorited any organizations! </h5>
	<h6> Please go to the recommendations page to view orgs </h6>
	<%= link_to "View Recommended Orgs", home_path, class: "modal-action modal-close waves-effect waves-green btn-flat" %>
	<div id="modal1" class="modal">
	    <div class="modal-content">
	      <h4>Uh-Oh!</h4>
	      <p>You have not favorited any organizations!</p>
	      <p>Please go to the recommendations page to view orgs!</p>
	    </div>
	    <div class="modal-footer">
	      <%= link_to "View Recommended Orgs", home_path, class: "modal-action modal-close waves-effect waves-green btn-flat" %>
	    </div>
	</div>
<% else %>
	<h4><%="#{current_user.student.first_name}"%>'s Dashboard</h4><br><br>
	<div class ="row">
		<div class="col s6">
			<div style="min-width: 310px; height: 400px; margin: 0 auto;">
			    <div id="container-speed" style="width: 500px; height: 400px; float: left"></div>
			</div>
		</div>
		<div class="col s6">
			<div id="container" style="min-width: 310px; height: 400px; margin: 0 auto"></div>
		</div>
		<!-- The statistical graph should go in here-->
		<div id="positions" style="display:none"><%= @positions %></div>
		<div id="stackchart" style="display:none"><%= @stackchart %></div>
	</div>

	<div class ="row">
	<% @commitments.each do |org| %>
			<div class="col s4">
	      <div class="card small">
	        <div class="card-content">
	          <span class="card-title activator grey-text text-darken-4" id="org_name"><b><%= org.name %></b><i class="mdi-navigation-more-vert right"></i></span>
	          <br>
	          <p style="overflow:hidden;display:-webkit-box;-webkit-line-clamp:3;-webkit-box-orient: vertical;"><%= raw org.description %></p>
	        </div>

	        <div class="card-action">
						<%= link_to "View Organization", organization_path(org) %>
						<% unless current_user.favorite_organizations.exists?(id: org.id) %>
							
							<%= link_to image_tag('unfavorite.png', size: "35x30", :style => ("padding-left:5px;"), class: "right"), favorite_organizations_path(organization_id: org.id), method: :post %>
						<% else %>
							<%= link_to image_tag('favorite.jpg', size: "35x30", :style => ("padding-left:5px;"), class: "right"), favorite_organization_path(org), method: :delete %>
						<% end %>
					</div>
	      </div>
	    </div>
		<% end %>
	</div>
<% end %>
</div>

	<script>

	$(document).ready(function(){
    // the "href" attribute of .modal-trigger must specify the modal ID that wants to be triggered
    $('.modal').modal({
    	dismissible: false
    });
  });

	lengthTotal = $('#positions').text().length

	if(lengthTotal <= 2) {
		$('#modal1').modal('open')
	}

	if(lengthTotal > 2) {
		hoursList= $('#positions').text().substring(1,lengthTotal-1).split(",")

		var hoursListInt = []

		hoursList.forEach(function(strHour){
			hoursListInt.push(parseInt(strHour))
		})

		function sumList(theList){
			var total = 0
			theList.forEach(function(element){
				total += element
			})
			return total
		}

		totalHours = sumList(hoursListInt)

			$(function () {

		    var gaugeOptions = {

		        chart: {
		            type: 'solidgauge'
		        },

		        title: 'Total Weekly Commitments (hours)',

		        pane: {
		            center: ['50%', '70%'],
		            size: '100%',
		            startAngle: -90,
		            endAngle: 90,
		            background: {
		                backgroundColor: (Highcharts.theme && Highcharts.theme.background2) || '#EEE',
		                innerRadius: '60%',
		                outerRadius: '100%',
		                shape: 'arc'
		            }
		        },

		        tooltip: {
		            enabled: false
		        },

		        // the value axis
		        yAxis: {
		            stops: [
		                [0.1, '#55BF3B'], // green
		                [0.5, '#DDDF0D'], // yellow
		                [0.9, '#DF5353'] // red
		            ],
		            lineWidth: 0,
		            minorTickInterval: null,
		            tickAmount: 2,
		            title: {
		                y: -150
		            },
		            labels: {
		                y: 16
		            }
		        },

		        plotOptions: {
		            solidgauge: {
		                dataLabels: {
		                    y: 5,
		                    borderWidth: 0,
		                    useHTML: true
		                }
		            }
		        }
		    };

		    // The speed gauge
		    var chartSpeed = Highcharts.chart('container-speed', Highcharts.merge(gaugeOptions, {
		        yAxis: {
		            min: 0,
		            max: 35,
		            title: {
		                text: 'Total Weekly Commitments (hours)'
		            }
		        },

		        credits: {
		            enabled: false
		        },

		        series: [{
		            name: 'Total Hours Spent',
		            data: [totalHours],
		            dataLabels: {
		                format: '<div style="text-align:center"><span style="font-size:25px;color:' +
		                    ((Highcharts.theme && Highcharts.theme.contrastTextColor) || 'black') + '">{y}</span><br/>' +
		                       '<span style="font-size:12px;color:silver">hours</span></div>'
		            },
		            tooltip: {
		                valueSuffix: ' hours'
		            }
		        }]

		    }));

		});
	};

	$(function () {

	lengthTotal = $('#stackchart').text().length
	if(lengthTotal > 2) {

		var hash_string = $('#stackchart').html();
	    var st;
	    var interestList = hash_string.split(",");
	    console.log(interestList);
	    var hash_dict = [];
	    for (st in interestList) {
	    	console.log(interestList[st]);
	    	dict = {};
	    	var interest_pattern = /"(.*?)"/;
	    	var interest_value = interestList[st].match(interest_pattern);
	    	console.log("after matching name",interest_value[1]);
	    	dict['name'] = interest_value[1];

	    	var value_pattern = /\d+/;
	    	var real_count = interestList[st].match(value_pattern);
	    	console.log("after matching hour",real_count[0]);
	    	dict['data'] = [parseInt(real_count[0])];
	    	console.log('dict',dict);
	    	hash_dict.push(dict);
	    }
			
	    Highcharts.chart('container', {
	        chart: {
	            type: 'column'
	        },
	        title: {
	            text: ''
	        },
	        xAxis: {
	            categories: ['Hour Breakdown']
	        },
	        yAxis: {
	            min: 0,
	            title: {
	                text: 'Total Hours'
	            },
	            stackLabels: {
	                enabled: true,
	                style: {
	                    fontWeight: 'bold',
	                    color: (Highcharts.theme && Highcharts.theme.textColor) || 'gray'
	                }
	            }
	        },
	        legend: {
	            align: 'right',
	            x: -30,
	            verticalAlign: 'top',
	            y: 25,
	            floating: false,
	            backgroundColor: (Highcharts.theme && Highcharts.theme.background2) || 'white',
	            borderColor: '#CCC',
	            borderWidth: 1,
	            shadow: true
	        },
	        tooltip: {
	            headerFormat: '<b>{point.x}</b><br/>',
	            pointFormat: '{series.name}: {point.y}<br/>Total: {point.stackTotal}'
	        },
	        plotOptions: {
	            column: {
	                stacking: 'normal',
	                dataLabels: {
	                    enabled: true,
	                    color: (Highcharts.theme && Highcharts.theme.dataLabelsColor) || 'white'
	                }
	            }
	        },
	        series: hash_dict
	    });
	}
	});
	</script>